# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec features) \
#  .select{|d| Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")}

directories %w(..) .select{|d| Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")}

guard 'livereload' do
  watch(%r{build/.+\.(css|js|html)$})
end

guard 'shell' do
  watch(%r{(src/.+)})   { `cd ..; make` }
end
